### PR TITLE
introduce melange-examples

### PR DESCRIPTION
**Pull request by jchavarri**
This is a reorganization of the repository to make room for more examples, so that it becomes easier for the community to contribute or update them in a single place.

It is based on [aantron's amazing Dream's `example` folder](https://github.com/aantron/dream/tree/8140a600e4f9401e28f77fee3e4328abdc8246ef/example).

### CODE REVIEW

**Comment by jchavarri** [comment]
@anmonteiro @davesnx if you are ok with this, I will rename the repo to `melange-examples` after merge.

**Comment by davesnx** [comment]
I would still name it opam-template and have a 1 file thing with the basics and keep the examples to grow, thoughts?

**Comment by jchavarri** [comment]
> and have a 1 file thing with the basics and keep the examples to grow

i don't understand this.

**Comment by davesnx** [comment]
My suggestion is to keep the `src/ReactApp.re` and `src/dune`

**Comment by anmonteiro** [comment]
> Maybe it would be better to create a new repo melange-examples altogether and move this PR over there? So we can leave this one as the minimal expression of a Node and React apps?

I think this is a better idea, too. That way, we:

- have a github template you can use as a starter with 1-click
- have a github repo with more examples and other use cases that you can pick and choose

**Comment by jchavarri** [comment]
Ok, I will move this to newly created https://github.com/melange-re/melange-examples.

**Pull request closed without merging**
