### PR TITLE
Migrate to reason-react next version with React 18

### PR DESCRIPTION
**Pull request by davesnx**

### CODE REVIEW

**Comment by jchavarri** [comment]
Ftr i am holding on this until there's a version published on opam repository, as I think the template should be usable without pinning. But if you feel strongly about something else, please discuss.

**Comment by davesnx** [comment]
Yes, same. Until we publish a new opam template with 0.14 I will keep this PR open

**Comment by jchavarri** [comment]
I updated the `react` and `react-dom` versions in #34, and reason-react 0.14.0 is picked automatically from opam repo, so the diff now is only `createRoot` change. Merging 🚢  thanks @davesnx !

**Comment by anmonteiro** [comment]
thanks for doing this

**Pull request merged**
